<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>
    <ItemGroup>
        <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.0.10" />
        <PackageReference Include="Avalonia.Desktop" Version="11.0.10" />
        <PackageReference Include="Avalonia.Diagnostics" Version="11.0.10" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.10" />
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TypingTrainer.Core\TypingTrainer.Core.csproj" />
        <ProjectReference Include="..\TypingTrainer.Data\TypingTrainer.Data.csproj" />
    </ItemGroup>

</Project>
